const coursesData = [
  {
    "id": "cs111",
    "header": "CS 111",
    "title": "Intro to Computer Science",
    "description": "Teaches how to design, develop, reason about, and test programs. Topics include data types, control structures, functions, objects, basic algorithms, and problem-solving strategies.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": true,
    "prerequisites": [], // No prerequisites
    "skills": ["Problem-solving", "Basic programming concepts"],
    "deliveryMethod": ["In-person", "Online"],
    "requirement": ["requirement1"]
  },
  {
    "id": "cs180",
    "header": "CS 180",
    "title": "Intro to Data Science",
    "description": "Statistics; linear algebra; machine learning; data cleaning and visualization.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": [],
    "skills": ["Statistics", "Linear algebra", "Machine learning", "Data cleaning", "Data visualization"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs202",
    "header": "CS 202",
    "title": "Software Engineering Lab 1",
    "description": "The first of three experiential learning labs that will provide students with hands-on experience.",
    "credits": 1,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": [],
    "skills": ["Hands-on software engineering experience"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs203",
    "header": "CS 203",
    "title": "Software Engineering Lab 2",
    "description": "The second of three experiential learning labs that will provide students with hands-on experience.",
    "credits": 1,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["CS 202"],
    "skills": ["Advanced software engineering practices"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs204",
    "header": "CS 204",
    "title": "Software Engineering Lab 3",
    "description": "The third of three experiential learning labs that will provide students with hands-on experience.",
    "credits": 1,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["CS 203"],
    "skills": ["Advanced software engineering practices"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs224",
    "header": "CS 224",
    "title": "Computer Systems",
    "description": "How a computer works to execute sequential code: low level data representation and instruction processing.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": true,
    "prerequisites": ["CS 111"],
    "skills": ["Low-level data representation", "Instruction processing"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs235",
    "header": "CS 235",
    "title": "Data Structures",
    "description": "Fundamental data structures and algorithms; basic algorithm analysis.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": true,
    "prerequisites": ["CS 111"],
    "skills": ["Data structures", "Algorithms", "Basic algorithm analysis"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs236",
    "header": "CS 236",
    "title": "Discrete Structure",
    "description": "Introduction to grammars and parsing; predicate and propositional logic; proof techniques.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": true,
    "prerequisites": ["CS 111"],
    "skills": ["Grammars", "Parsing", "Predicate and propositional logic", "Proof techniques"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs312",
    "header": "CS 312",
    "title": "Algorithm Design and Analysis",
    "description": "Advanced algorithm analysis, design techniques, graph algorithms, probabilistic algorithms, and parallel computing.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": true,
    "prerequisites": ["CS 235", "CS 236"],
    "skills": ["Advanced algorithm analysis", "Design techniques", "Graph algorithms"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs324",
    "header": "CS 324",
    "title": "Systems Programming",
    "description": "Operating systems, concurrent programming, process management, memory management, file systems, and networking.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": true,
    "prerequisites": ["CS 224"],
    "skills": ["Operating systems", "Concurrent programming", "Process management"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs340",
    "header": "CS 340",
    "title": "Software Design & Testing",
    "description": "Software development methodologies, object-oriented design patterns, testing strategies, and software maintenance.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": true,
    "prerequisites": ["CS 235"],
    "skills": ["Software development methodologies", "Object-oriented design patterns", "Testing strategies"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs330",
    "header": "CS 330",
    "title": "Programming Languages",
    "description": "Programming language paradigms, syntax and semantics, type systems, functional programming, and language implementation techniques.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 236"],
    "skills": ["Programming language paradigms", "Syntax and semantics", "Type systems", "Functional programming"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs345",
    "header": "CS 345",
    "title": "Operating Systems Design",
    "description": "Process management, memory allocation, file systems, device management, and distributed systems concepts.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 324"],
    "skills": ["Process management", "Memory allocation", "File systems"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs355",
    "header": "CS 355",
    "title": "Interactive Graphics",
    "description": "2D graphics programming, user interface design, event handling, and interactive applications development.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 235"],
    "skills": ["2D graphics programming", "User interface design", "Event handling"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs450",
    "header": "CS 450",
    "title": "Computer Graphics",
    "description": "3D graphics, rendering, geometric modeling, animation, visualization techniques, and graphics programming.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 355"],
    "skills": ["3D graphics", "Rendering", "Geometric modeling"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs465",
    "header": "CS 465",
    "title": "Computer Security",
    "description": "Cryptography, network security, authentication, access control, and software security principles.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 324"],
    "skills": ["Cryptography", "Network security", "Authentication"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs470",
    "header": "CS 470",
    "title": "Artificial Intelligence",
    "description": "Machine learning, neural networks, natural language processing, and expert systems development.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 111"],
    "skills": ["HTML", "CSS", "JavaScript", "Server-side programming"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5"]
  },
  {
    "id": "cs260",
    "header": "CS 260",
    "title": "Web Programming",
    "description": "HTML, CSS, JavaScript, and server-side programming for web applications.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 111"],
    "skills": ["HTML", "CSS", "JavaScript", "Server-side programming"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs356",
    "header": "CS 356",
    "title": "Mobile Application Development",
    "description": "Design and development of mobile applications for iOS and Android platforms.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 235"],
    "skills": ["Mobile app design and development for iOS and Android"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs401",
    "header": "CS 401",
    "title": "Ethics in Computer Science",
    "description": "Ethical issues in computing, privacy, intellectual property, and professional responsibility.",
    "credits": 2,
    "semesters": ["F", "W"],
    "isCore": true,
    "prerequisites": [],
    "skills": ["Ethical issues in computing", "Privacy", "Intellectual property"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs452",
    "header": "CS 452",
    "title": "Database Systems",
    "description": "Relational database design, SQL, database management systems, and data warehousing.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 235"],
    "skills": ["Relational database design", "SQL", "Database management systems"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs460",
    "header": "CS 460",
    "title": "Computer Networks",
    "description": "Network protocols, architecture, security, and distributed systems.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 324"],
    "skills": ["Network protocols", "Architecture", "Security"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs472",
    "header": "CS 472",
    "title": "Machine Learning",
    "description": "Supervised and unsupervised learning algorithms, neural networks, and deep learning.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 312"],
    "skills": ["Supervised and unsupervised learning algorithms", "Neural networks"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs480",
    "header": "CS 480",
    "title": "Software Engineering",
    "description": "Large-scale software development, project management, and software architecture.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 340"],
    "skills": ["Large-scale software development", "Project management"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs486_1",
    "header": "CS 486",
    "title": "Verification and Validation",
    "description": "Software testing techniques, test-driven development, and formal verification methods.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 340"],
    "skills": ["Software testing techniques", "Test-driven development"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs490r",
    "header": "CS 490R",
    "title": "Special Topics in Computer Science",
    "description": "Advanced topics in computer science, varying by semester.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["Varies by topic"],
    "skills": ["Advanced topics in computer science"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs494",
    "header": "CS 494",
    "title": "Capstone I",
    "description": "First part of the senior project course, focusing on project planning and design.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": true,
    "prerequisites": ["Senior standing"],
    "skills": ["Project planning and design"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs495",
    "header": "CS 495",
    "title": "Capstone II",
    "description": "Second part of the senior project course, focusing on implementation and presentation.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": true,
    "prerequisites": ["CS 494"],
    "skills": ["Project implementation and presentation"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "cs240",
    "header": "CS 240",
    "title": "Advanced Programming Concepts",
    "description": "Object-oriented programming, design patterns, and advanced language features.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 235"],
    "skills": ["Object-oriented programming", "Design patterns"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement5,requirement6"]
  },
  {
    "id": "cs252",
    "header": "CS 252",
    "title": "Introduction to Computational Theory",
    "description": "Formal languages, automata theory, and computability.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 236"],
    "skills": ["Formal languages", "Automata theory", "Computability"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]

  },
  {
    "id": "cs301",
    "header": "CS 301",
    "title": "Algorithms and Complexity",
    "description": "Advanced algorithm design, complexity analysis, and NP-completeness.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 236"],
    "skills": ["Formal languages", "Automata theory", "Computability"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs360",
    "header": "CS 360",
    "title": "Internet Programming",
    "description": "Client-server architecture, RESTful APIs, and full-stack web development.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 260"],
    "skills": ["Client-server architecture", "RESTful APIs", "Full-stack web development"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs405",
    "header": "CS 405",
    "title": "Creating and Managing a Software Business",
    "description": "Entrepreneurship in software, business models, and startup strategies.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": [],
    "skills": ["Entrepreneurship in software", "Business models", "Startup strategies"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs412",
    "header": "CS 412",
    "title": "Distributed Systems",
    "description": "Principles and paradigms of distributed computing systems.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 324"],
    "skills": ["Distributed computing principles", "Scalability", "Fault tolerance"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs428",
    "header": "CS 428",
    "title": "Software Engineering",
    "description": "Software development processes, requirements engineering, and project management.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 340"],
    "skills": ["Software development processes", "Requirements engineering", "Project management"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs431",
    "header": "CS 431",
    "title": "Artificial Intelligence",
    "description": "Knowledge representation, reasoning, and machine learning techniques.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 312"],
    "skills": ["Knowledge representation", "Reasoning", "Machine learning techniques"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs455",
    "header": "CS 455",
    "title": "Computer Graphics",
    "description": "3D modeling, rendering, and animation techniques.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 355"],
    "skills": ["3D modeling", "Rendering", "Animation techniques"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs462",
    "header": "CS 462",
    "title": "Large-scale Distributed Systems",
    "description": "Design and implementation of scalable distributed systems and cloud computing.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 412"],
    "skills": ["Scalable system design", "Cloud computing", "Parallel processing"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs474",
    "header": "CS 474",
    "title": "Deep Learning",
    "description": "Neural network architectures, training techniques, and applications in various domains.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 472"],
    "skills": ["Neural network architectures", "Training techniques", "Deep learning applications"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs478",
    "header": "CS 478",
    "title": "Introduction to Data Mining",
    "description": "Data preprocessing, association rules, clustering, and classification techniques.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 312"],
    "skills": ["Data preprocessing", "Association rules", "Clustering", "Classification techniques"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs484",
    "header": "CS 484",
    "title": "Parallel Processing",
    "description": "Parallel algorithms, architectures, and programming models.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 324"],
    "skills": ["Parallel algorithms", "Parallel architectures", "High-performance computing"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs486_2",
    "header": "CS 486",
    "title": "Verification and Validation",
    "description": "Software testing techniques, test-driven development, and formal verification methods.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": ["CS 340"],
    "skills": ["Software testing techniques", "Test-driven development", "Formal verification"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs493r",
    "header": "CS 493R",
    "title": "Computing for Good",
    "description": "Applying computer science skills to solve real-world problems in non-profit and humanitarian contexts.",
    "credits": 3,
    "semesters": ["F", "W"],
    "isCore": false,
    "prerequisites": [],
    "skills": ["Applying CS to non-profit work", "Humanitarian computing solutions"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs497r",
    "header": "CS 497R",
    "title": "Undergraduate Research",
    "description": "Directed research in computer science under faculty supervision.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["Instructor permission"],
    "skills": ["Research methodologies", "Experimentation", "Technical writing"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs498r",
    "header": "CS 498R",
    "title": "Undergraduate Teaching Assistant",
    "description": "Assisting in teaching undergraduate computer science courses.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["Instructor permission"],
    "skills": ["Teaching assistance", "Grading", "Mentorship"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "cs501",
    "header": "CS 501",
    "title": "Advanced Algorithms",
    "description": "In-depth study of advanced algorithmic techniques and analysis.",
    "credits": 3,
    "semesters": ["F"],
    "isCore": false,
    "prerequisites": ["CS 312"],
    "skills": ["Advanced algorithmic techniques", "Computational complexity", "Algorithm analysis"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement6"]
  },
  {
    "id": "math112",
    "header": "MATH 112",
    "title": "Calculus 1",
    "description": "Introduction to differential and integral calculus of one variable.",
    "credits": 4,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["MATH 111"],
    "skills": ["Differential calculus", "Integral calculus"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "math113",
    "header": "MATH 113",
    "title": "Calculus 2",
    "description": "Continuation of Calculus 1, including techniques of integration, series, and polar coordinates.",
    "credits": 4,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["MATH 112"],
    "skills": ["Techniques of integration", "Series", "Polar coordinates"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement1"]
  },
  {
    "id": "math214",
    "header": "MATH 214",
    "title": "Linear Algebra",
    "description": "Matrix theory, vector spaces, linear transformations, and eigenvalues.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["MATH 113"],
    "skills": ["Matrix theory", "Vector spaces", "Linear transformations"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement2"]
  },
  {
    "id": "math215",
    "header": "MATH 215",
    "title": "Multivariable Calculus",
    "description": "Calculus of functions of several variables, including partial derivatives and multiple integrals.",
    "credits": 4,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["MATH 113"],
    "skills": ["Partial derivatives", "Multiple integrals"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement2"]
  },
  {
    "id": "math302",
    "header": "MATH 302",
    "title": "Differential Equations",
    "description": "Introduction to ordinary differential equations and their applications.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["MATH 215"],
    "skills": ["Ordinary differential equations", "Applications of differential equations"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement4"]
  },
  {
    "id": "phys121",
    "header": "PHYS 121",
    "title": "Physics 1",
    "description": "Mechanics, heat, and sound.",
    "credits": 4,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["MATH 112"],
    "skills": ["Mechanics", "Heat", "Sound"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement2"]
  },
  {
    "id": "stat121",
    "header": "STAT 121",
    "title": "Principles of Statistics",
    "description": "Introduction to statistical methods and data analysis.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["MATH 112"],
    "skills": ["Statistical methods", "Data analysis"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement3"]
  },
  {
    "id": "stat201",
    "header": "STAT 201",
    "title": "Intermediate Statistics",
    "description": "Continuation of introductory statistics, including hypothesis testing and regression analysis.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["STAT 121"],
    "skills": ["Hypothesis testing", "Regression analysis"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement3"]
  },
  {
    "id": "stat330",
    "header": "STAT 330",
    "title": "Applied Statistics",
    "description": "Application of statistical methods to real-world problems.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": ["STAT 201"],
    "skills": ["Statistical methods", "Real-world applications"],
    "deliveryMethod": ["In-person"],
    "requirement" : ["requirement4"]
  },
  {
    "id": "wrtg316",
    "header": "WRTG 316",
    "title": "Technical Communication",
    "description": "Focuses on the principles and practices of effective technical communication, including writing, editing, and presenting technical information.",
    "credits": 3,
    "semesters": ["F", "W", "SP", "SU"],
    "isCore": false,
    "prerequisites": [],
    "skills": ["Technical writing", "Editing", "Presenting technical information"],
    "deliveryMethod": ["In-person", "Online"],
    "requirement" : ["requirement2"]
  }
];

export default coursesData;
